### ISSUE TITLE
Enable limited admin interface for all users

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#100]
Currently, only admin users are permitted to log into the admin interface and see any of the statistics.

The admin interface's components should be broken down into what is accessible based on the user's admin status. Checking `user.admin === true` will suffice for this. (remember that these checks must happen on both the frontend and backend controllers.)

Basically everything that is currently available in the admin interface must be set as viewable and modifiable only for admin users. The only thing we can start by adding for all users is the ability to log in and change one's own password.

(Hint: for restricting access on the backend, check the `routes/admin.route.js` file, and add routes / controller methods that don't have to be subject to `authCtrl.ensureAdmin`. :) )

**Comment by GuillaumeCz** [comment]
This issue was moved to GuillaumeCz/sylow#6
