### ISSUE TITLE
Validate document data objects on submission

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#13]
The server should verify that a client is sending it a valid document using the embedded JSON Schema before it saves it or performs other actions on it. To do so:

- use the `ajv` library (probably)
- look at the POSTed document's `data` key
- get this object's JSON Schema from a remote server using `ajv`
  - first, make sure this JSON Schema is hosted from a whitelisted server in the configuration
- validate the document's `data` key against said schema

**Comment by GuillaumeCz** [comment]
Do you mean that we may use the "[Asynchronous validation](https://github.com/epoberezkin/ajv#asynchronous-validation)" in order to do remote validation ?

**Comment by peakwinter** [comment]
@GuillaumeCz Correct :) I haven't yet finished setting up the server that hosts the schema, so this might not work yet.

**Comment by GuillaumeCz** [comment]
This issue was moved to GuillaumeCz/sylow#7
