### ISSUE TITLE
Use document collection population

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#14]
For all document collections that make reference to other collections, use population to create the field.

Also, create a `DocumentData` collection that stores the `data` keys of individual documents, and load them via population. This way we can only load specific versions if the document controller requests them.

http://mongoosejs.com/docs/populate.html

**Comment by GuillaumeCz** [comment]
Does it mean that we need to use the "Population" system to reference other documents in the attributes "references" of a document ? 
DocumentData should be an new Model with just an attribute "data" or I misunderstood something ? ;)

**Comment by peakwinter** [comment]
@GuillaumeCz Your understanding of the issue is correct, but I'm not convinced at the moment that this is the best way to go. I'd hold off on this for the time being. :)
