### ISSUE TITLE
Minor changes to Entity model and validation

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#20]
* Change Entity validation in `config/param-validation.js` to allow EITHER a `username` and `domain` OR an `entityName`
* Make public key non-required on both Mongoose schema and in param validation.

**Comment by GuillaumeCz** [comment]
I face few problems with this bugfix. Ref : https://github.com/hapijs/joi/issues/588 --> XOR beetwen username/domain and entityName | https://github.com/hapijs/joi/issues/537 --> Multiple "when"

**Comment by peakwinter** [comment]
@GuillaumeCz Yeah, that's annoying. Not important that it be mutually exclusive. It can accept both username/domain and entityName but it will default to using entityName if it is provided at all. How about that?

**Comment by GuillaumeCz** [comment]
I think that your idea will facilitate this issue. I'll try this
