### ISSUE TITLE
Encrypted filtering

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#25]
Encrypted filtering is possible by creating a series of encrypted key/values on each submission on the client side, then making these tags queryable via the document retrieval API. For example, when an event that was created on June 12th, 2017 is saved, it can be automatically created with the following tags:

```
{
  "createdMonth": "6",
  "createdDay: "12",
  "createdYear": "2017"
}
```

When these keys and values are encrypted, the client can reproduce the same keys and values deterministically and the server can use these in its filtering. So if the client is a calendar application and wants to show all of the events created on June 12th, 2017, it can send the encrypted version of each key and each value to the server, which will match with the event created prior. The server doesn't know what is being searched for, only that a certain document corresponds to the provided tags.

----

To make this possible:

* Convert `tags` from a simple list to a filterable object.
* Create a virtual method that returns a list of keys for each document.
* In the filtering function, perform in two stages: first by documents that have the provided keys present, then filter further by the proper values for those keys.

**Comment by GuillaumeCz** [comment]
During the first step of the filtering : Do we have to keep the documents which have exactly the same tag's keys as the parameter ? Or only some of them that have at least one ?

**Comment by peakwinter** [comment]
@GuillaumeCz This is another case of "I'm not yet sure how I want this to work exactly" :joy:

**Comment by GuillaumeCz** [comment]
xD ok I see

**Comment by GuillaumeCz** [comment]
I realized that the actual tag system is not working as expected. This issue could be seen as a good occasion to refactor and make work all these. I think (and hope) that I'm willing to succeed ! :D
