### ISSUE TITLE
Admin Settings Page

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#31]
Be able to:

* return all (non-sensitive) config values in a view
* modify all of these values and save them back to the server

**Comment by GuillaumeCz** [comment]
In order to modify the setting values, do we have to create a Model and a Controller named "Config" to update them such as the other common models ?

**Comment by peakwinter** [comment]
@GuillaumeCz Controller yes, model no. The configuration is loaded through `config/config.js`. Changed values should be saved to `.env` when new ones are provided. Note that only variables starting with `SY_*` should be modifiable via this interface, and it should be dynamic because there will be other values we will add at a later date.

**Comment by GuillaumeCz** [comment]
"On-hold" Because we don't know what to do with the updated settings yet (where and how do we keep it ?)

**Comment by peakwinter** [comment]
The saving of the config file should go something like this:

* Check for a `.env` file in the app root. If there isn't one, do nothing and do not continue with the following steps.
* Create a new object with the modifiable config values (i.e. are not in `unvariableConfig`). Convert their names in this new object to an underscored version with `SY_` in front of it. (There are certainly NPM libraries out there that will convert the camelcasing to underscoring)
* Iterate over the lines in the .env file. Split each line on the equals sign. If the line's key equals one of the config values we just created, set the line's value as necessary.
* Write the new file in place.
