### ISSUE TITLE
RSA public/private key generation

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#33]
- Utility functions should be created to handle RSA public/private key generation.
- These functions should be able to generate new RSA public/private keys, password protected or unprotected, and return them as base64 strings (i.e. PEM format without the header/footer).
- For the time being, this will be only used for generating keys for authoritative Server records. Entities will generate their keys on the client side.
- Key generation should ensure there is enough entropy available for the operation.

**Comment by GuillaumeCz** [comment]
https://www.npmjs.com/package/node-forge#rsa
