### ISSUE TITLE
DNS-based discovery functions

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#34]
- Local servers will look for remote servers using a DNS lookup on the remote domain's SRV record. In the following example, the record tells Sylow servers to send all requests for this domain to `sylowsrv.example.com:8080`:
  - `_sylow._tcp.example.com.  86400 IN   SRV 10 100 8080 sylowsrv.example.com.`
  - In this way, someone can host their Sylow server on a separate subdomain and/or port from the rest of their site, but still have simple entity names like `jake@example.com`.
  - If the remote domain in question does not have a Sylow SRV record, the local server assumes it is at the root at port 80, i.e. `example.com:80`.

**Comment by GuillaumeCz** [comment]
This issue was moved to GuillaumeCz/sylow#8
