### ISSUE TITLE
Server model

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#35]
- A Server model should be created, tasked with keeping track of different information for local and remote servers. It should have the following properties:
    - `id`: UUID unique to this server across the network
    - `created` and `updated` timestamps
    - `domain`: required string corresponding to the domain that the server handles requests for
    - `name`: optional string so that people can name their servers
    - `description`: optional string (markdown-flavoured) so people can give descriptions or operating rules for their servers
    - `contacted`: timestamp representing the last time these two servers had contact
    - `keys`: an object with `public` (required string) and `private` (optional string) values
    - `authoritative`: boolean value, true if this server record corresponds to the local server

**Comment by GuillaumeCz** [comment]
What about creating a unique id for each server in Sylow and another parameter with the IP address seen as an unique Id across the network ? @peakwinter

**Comment by peakwinter** [comment]
@GuillaumeCz I thought of that awhile ago, but IP addresses can be transient. For example, if someone is using a server that is load-balanced or uses floating IPs. If we can keep most server identification down to domain names and unique UUIDs of Server records, I think it will work fine. The added cost of occasional DNS lookups shouldn't be overwhelming.
