### ISSUE TITLE
Server controller

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#36]
- A Server controller should be created to allow management of Server model records.
   - A Server model record that is marked as being `authoritative` is checked for at each boot. If one is not found, a critical error is raised (see Authoritative server records issue). Instead of keeping track of the domain in an environment variable, the server takes the domain from this first found record and considers it to be its own domain.
   - Server records can be created by remote servers with no authentication (see "Server record exchanges" issue for further information.) They can only be retrieved, updated or deleted by the local server or the remote server that it corresponds to.

**Comment by GuillaumeCz** [comment]
- [ ] Validation schema (param-validation) 
- [ ] Tests
