### ISSUE TITLE
Server record exchanges

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#37]
- Non-authoritative Server records are created by remote servers on the local one at the moment of first contact in the following way:
    - The remote server attempts to contact the local server (e.g. via the sending of a new document).
    - The local server sends back an HTTP code and message that tells the remote server it needs more information from it first.
    - The remote server responds with another call to create its own Server record on the local server, which is accepted by the local server. The local server sends its own Server record in response.
    - The remote server then retries its request.
    - Most likely however, instead of doing all of this, a remote server will voluntarily send its Server record to the local server if it can see that it doesn't have any corresponding record for the local server.

**Comment by GuillaumeCz** [comment]
This issue was moved to GuillaumeCz/sylow#9
