### ISSUE TITLE
Admin page for Server details

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#39]
- Show information regarding the current server (name, description) as well as a way to modify this information on a new Server page (second one in the navigation menu).
   - Allow for the downloading of the raw Server record in its entirety. The user can then backup this record locally in case their server ever gets wiped.

**Comment by GuillaumeCz** [comment]
Do we provide a way for admin to change any of the keypair ?

**Comment by peakwinter** [comment]
No, there is no need to update the server record via the CLI for now. Eventually that will be built into the web interface.

**Comment by GuillaumeCz** [comment]
Ok, so I will do that in the admin interface
