### ISSUE TITLE
S3 driver for Files controller

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#46]
Amazon S3 bucket integration should be provided for the Files controller. Instead of generating a UUID, authorizing its use and saving an uploaded file to the server's own hard drive, POST requests to `/api/file` should instead generate an Amazon S3 signed URL that the client can use to upload their file.

The config controller must be updated to take all the values necessary to properly configure a connection to the S3 API, as well as the ability to choose which file storage method the server operator wants to use (S3 or the existing local storage method).

**Comment by GuillaumeCz** [comment]
This issue was moved to GuillaumeCz/sylow#11
