### ISSUE TITLE
Document controller

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#6]
Ensure that endpoints exist for the creation, modification and deletion of documents.

PUT/DELETE endpoints for a given document should be restricted to devices that are both 1) properly registered with the system using OAuth2, and 2) associated with the entity that created the device and the document in question.

Documents should be returned to devices per their `public` flag. All devices can see documents flagged as `public`, while only devices belonging to the entity that created them should be able to see documents that are not `public`.

**Comment by GuillaumeCz** [comment]
Notes : After creating a client and entity, use Postman to create an OAuth2 access token using the following parameters:
Auth URL: http://localhost:4040/authorize
Access Token URL: http://localhost:4040/token
Client ID: postman
Client Secret: xxxxxx
Grant Type: Authorization Code
Request access token locally
