### ISSUE TITLE
Make statistics section prettier

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#64]
1. There is a bug in the statistics section that shows the header above each content type, instead of only once in the table.
![screenshot from 2017-07-31 13-13-26](https://user-images.githubusercontent.com/997174/28789287-b529602e-75f2-11e7-8572-ecf4f1e72412.png)

2. We should look into a nice graphics / charts library that would allow us to show some simple visualizations in this section, above or alongside the content types table. Examples of pertinent visualizations: bar or pie chart of the number of each content type present in the database; number of servers contacted today vs. yesterday and the day before; number of documents by encryption type; number of authoritative entities created by month; number of non-authoritative entities created by month; etc. Ultimately it would also be cool to have a dropdown for selecting the type of visualization to display at a given time, so that the screen doesn't become overloaded with different widgets.

**Comment by GuillaumeCz** [comment]
PR #65 is for the first part of this issue.

**Comment by GuillaumeCz** [comment]
This issue was moved to GuillaumeCz/sylow#13
