### ISSUE TITLE
Enhancements to Entity edit admin page

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#70]
The entity edit page `/entities/:entityId` should show a couple of basic statistics for that entity:

* number of documents that have that entity's ID as its `entityId`
* the date the entity was created

The entity edit page should also include an export function in the same manner as the Server page's export function.

**Comment by GuillaumeCz** [comment]
Est-ce qu'on ajoute des liens vers ces documents ou on se contente de dire que telle entitié est reliée a x documents ?

**Comment by GuillaumeCz** [comment]
Est-ce qu'on met la possibilité d'inserer un lien vers les documents liés ?

**Comment by peakwinter** [comment]
@GuillaumeCz Non, pas besoin. Seulement les statistiques seront nécessaires !
