### ISSUE TITLE
Implement API access scopes

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#72]
The API must allow for specified scopes, so that OAuth2 clients can only perform certain actions based on the scopes that they are registered with.

* A list of scopes must be hardcoded into the application. These scopes should include `create_x`, `read_x`, `update_x`, and `delete_x` for each model in the application, where `x` corresponds to the name of the model.
* The scope selector on the Client create/update page should be changed to a multiple selection box, using the hardcoded list of possible scopes as base data. The scopes will be stored on the client and accessToken models as a space-separated string field.

**Comment by GuillaumeCz** [comment]
This issue was moved to GuillaumeCz/sylow#15
