### ISSUE TITLE
Update Docker config to use non-standard Mongo port

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#74]
In order to allow multiple instances of MongoDB to run on the system at once (system-level and inside a Docker container), the `MONGO_PORT` value should be changed in the appropriate places of the `docker-compose` configuration.

**Comment by GuillaumeCz** [comment]
Can we put any port number ?

**Comment by peakwinter** [comment]
@GuillaumeCz I'd do the original port number + 1
