### ISSUE TITLE
Improvements to Postman configuration

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#88]
The Postman configurations should be improved to include more examples of API connections. Currently there are only options for creating an entity (users), but it would be nice to have some methods for creating sample documents or uploading files.

**Comment by GuillaumeCz** [comment]
Hello ;) 
Je bloque un peu pour générer un token OAuth via Postman pour pouvoir créer des documents. Pourrais tu me rappeler la série d'étape pour pouvoir en obtenir un ? ;)
Je pense que j'ai compris comment faire le tout via les pre-request scripts mais je ne parviens pas à me souvenir de tout xD

**Comment by GuillaumeCz** [comment]
Hello ! 
Comment est-ce que je peux faire pour générer et utiliser un token d'authentification utilisable dans une collection Postman ?
Dans le sens où pour créer au moins une entité et un client être authentifié, pareil pour les documents.

Est-ce qu'on considere que cette collection Postman peut être vu comme un jeu de données de base pour faire fonctionner Sylow ? 
ou seulement demeurer à titre d'exemples pour les differentes possibilités (montrer la structure des requetes, sans prévoir qu'elles fonctionnent) ? 

Je te remercie d'avance pour tes réponses ;)

**Comment by peakwinter** [comment]
Salut @GuillaumeCz :D

Je dirais que tu pourrais utiliser le système des Variables et Environnements qui est déjà disponible dans Postman, à voir : https://www.getpostman.com/docs/postman/environments_and_globals/variables

Je ne sais pas à quel point ces méthodes sont utilisables à partir des fichiers JSON que Postman va créer, mais c'est un début pour investiguer davantage.

Ces améliorations à notre config Postman de base ne vont pas servir à populer un serveur avec des données, mais seulement pour montrer la structure et donner la capacité à un développeur de plus facilement interéagir avec l'API et de mettre ses propres valeurs là où elles devraient être. :D


Merci !

**Comment by GuillaumeCz** [comment]
Ok super ! 
J'avais déjà ciblé le fait qu'il fallait utiliser les variables et environnements ! Je vais essayé de m'en sortir avec tout ça ;) 
Merci ! :D

**Comment by GuillaumeCz** [comment]
This issue was moved to GuillaumeCz/sylow#16
