### ISSUE TITLE
Add favicon.ico

### ISSUE THREAD

**Issue by 20th** [SylowTech/sylow#90]
This projet is really lacking a favicon! The address bar looks sad without it.

Proposal: add a favicon based on the current logo.

**Comment by 20th** [comment]
The _Obsessive favicon cheat sheet_ suggests to have a `/favicon.ico` file at the project root for maximum compatibility.

It can be easily accomplished with the `serve-favicon` middleware for `express` – https://github.com/expressjs/serve-favicon – if the project can afford to have a new dependency on this package.

**Comment by peakwinter** [comment]
Looks good!

**Comment by nitish24p** [comment]
Is anyone doing this?
I can pick it up if not
