### ISSUE TITLE
Document API using Swagger

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#96]
In addition to maintaining a client configuration for Postman with which the API can be tested by developers, it would be a good idea to establish a documentation for the API as a whole, so that all endpoints and parameters can be logged.

Swagger (https://swagger.io/swagger-editor/) is a cool utility that allows for the description of APIs in YAML file format, which can then be used to generate a fancy documentation website. We should use Swagger to generate some API documentation. Existing endpoints and methods can be found in the `routes` directory, while supported parameters can be found in `config/param-validation.js`.

This will help immensely with the development of client libraries and applications!

**Comment by GuillaumeCz** [comment]
This issue was moved to GuillaumeCz/sylow#17
