### ISSUE TITLE
Create a First Run landing page

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#97]
When the admin user first logs in to the admin interface, a special page should be presented to them. This page should welcome them to the Sylow universe, and present them with some basic information about what Sylow is designed to do.

This can be done by storing a value in the configuration, like `SHOW_FIRST_RUN`, which is `true` by default, but set to `false` once the user acknowledges the first run landing page (clicks OK at the bottom of the page).

The initial information to put on this page can be taken as a sample from the project website (https://sylow.info). I can provide more suitable "final" information later, the most important part is to start with the initial page :)

**Comment by GuillaumeCz** [comment]
This issue was moved to GuillaumeCz/sylow#18
