### ISSUE TITLE
Create file storage statistics section

### ISSUE THREAD

**Issue by peakwinter** [SylowTech/sylow#99]
When uploaded files are stored to disk (i.e. if `SYLOW_FILE_SYSTEM_PATH` is set; the only possible option at this stage), a statistics section should be shown on the admin's home page showing:

* the amount of files stored in this folder, and
* the total size of the entire folder (in the most appropriate unit; MB, GB, whatever)

**Comment by GuillaumeCz** [comment]
This issue was moved to GuillaumeCz/sylow#19
